In [2]:
## Consider the below code to answer further questions:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

##### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [17]:
"""
Answer:

1. The variable 'list_' is a python list containing string elements.
2. The variable 'array_list' is a NumPy array created from 'list_'.
"""

## Program to print the data types of given variables

print(f"The data type of variable 'list_' is {type(list_)}")
print(f"The data type of variable 'array_list' is {array_list.dtype}")

The data type of variable 'list_' is <class 'list'>
The data type of variable 'array_list' is <U1


##### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [37]:
## Program to print the data type of each and every element of both the variables list_ and array_list.

print("Data types of elements in 'list_':")
for i in list_:
    print("Element:",i, ", Type:",type(i))

print("\nData types of elements in 'array_list':")
for i in array_list:
    print("Element:",i, ", Type:",type(i))

Data types of elements in 'list_':
Element: 1 , Type: <class 'str'>
Element: 2 , Type: <class 'str'>
Element: 3 , Type: <class 'str'>
Element: 4 , Type: <class 'str'>
Element: 5 , Type: <class 'str'>

Data types of elements in 'array_list':
Element: 1 , Type: <class 'numpy.int64'>
Element: 2 , Type: <class 'numpy.int64'>
Element: 3 , Type: <class 'numpy.int64'>
Element: 4 , Type: <class 'numpy.int64'>
Element: 5 , Type: <class 'numpy.int64'>


##### Q3. Considering the following changes in the variable, array_list:
##### array_list = np.array(object = list_, dtype = int)
##### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_ylist? If so then print the data types 
##### of each and every element present in both the variables, list_ and array_list.

In [38]:
"""
Answer:

1. The elements in the 'list_' variable represent the string data type.
2. The elements in the 'array_list' variable now represent the NumPy integer data type.
3. The 'dtype=int' parameter in the np.array() function converted the string elements to integers in the 'array_list' variable.
"""

## Program to print the data type of each and every element of both the variables list_ and array_list.

array_list = np.array(object = list_, dtype = int)

print("Data types of elements in 'list_':")
for i in list_:
    print("Element:",i, ", Type:",type(i))

print("\nData types of elements in 'array_list':")
for i in array_list:
    print("Element:",i, ", Type:",type(i))

Data types of elements in 'list_':
Element: 1 , Type: <class 'str'>
Element: 2 , Type: <class 'str'>
Element: 3 , Type: <class 'str'>
Element: 4 , Type: <class 'str'>
Element: 5 , Type: <class 'str'>

Data types of elements in 'array_list':
Element: 1 , Type: <class 'numpy.int64'>
Element: 2 , Type: <class 'numpy.int64'>
Element: 3 , Type: <class 'numpy.int64'>
Element: 4 , Type: <class 'numpy.int64'>
Element: 5 , Type: <class 'numpy.int64'>


In [3]:
## Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

##### Q4. Write a code to find the following characteristics of variable, num_array:
##### (i) shape
##### (ii) size

In [49]:
## Program to print the shape and size of 'num_array' varible.

print(f"The 'shape' of variable 'num_array' is: {np.shape(num_array)}")

print(f"The 'size' of variable 'num_array' is: {np.size(num_array)}")

The 'shape' of variable 'num_array' is: (2, 3)
The 'size' of variable 'num_array' is: 6


##### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
##### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [73]:
## Program to create numpy array of 3*3 matrix containing zeros only.

zero_mat = np.zeros((3,3))

print(zero_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##### Q6. Create an identity matrix of shape (5,5) using numpy functions?
##### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [76]:
## Program to create  identity matrix of shape (5,5) using numpy function.

identity_mat = np.eye(5)
print(identity_mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
