##### Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application.

In [12]:
"""
Answer:

1. Min-Max scaling is a data preprocessing technique used in machine learning to scale and normalize the values of a feature or dataset to a specific range, 
typically between 0 and 1. 
2. This scaling method helps in ensuring that all features have a consistent scale and can be compared on an equal footing, which can be important for many 
machine learning algorithms that are sensitive to the magnitude of feature values.
3. Example:
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Sample dataset of exam scores
exam_scores = np.array([60, 70, 75, 85, 95])

# Create a MinMaxScaler object
min_max = MinMaxScaler()

# Fit and transform the data using the scaler
scaled_scores = min_max.fit_transform(exam_scores.reshape(5,1))

print("Original exam scores:", exam_scores)
print("Min-Max scaled scores:", scaled_scores)

"""
Now, all the exam scores are within the range of 0 to 1, making them suitable for input into machine learning algorithms that require features to be on a 
common scale.

"""

Original exam scores: [60 70 75 85 95]
Min-Max scaled scores: [[0.        ]
 [0.28571429]
 [0.42857143]
 [0.71428571]
 [1.        ]]


'\nNow, all the exam scores are within the range of 0 to 1, making them suitable for input into machine learning algorithms that require features to be on a \ncommon scale.\n\n'

##### Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.


In [17]:
"""
Answer:

1. The Unit Vector technique, also known as "Normalization" in some contexts, is a feature scaling method used in data preprocessing in machine learning. 
2. Its purpose is to scale the values of a feature such that they have a magnitude of 1 (unit length) while preserving the direction of the original data. 
3. Unit Vector scaling doesn't constrain the feature values to a specific range like [0, 1]. Instead, it ensures that all values of the feature are 
   scaled to have a magnitude of 1 while maintaining their relative proportions.
4. Example:

"""

from sklearn.preprocessing import normalize
import numpy as np

# Sample dataset of 2D vectors
vectors = np.array([[3, 4], [1, 2], [5, 5], [2, 3]])

# Normalize the vectors
normalized_vectors = normalize(vectors)

print("Original vectors:")
print(vectors)
print("Normalized vectors (unit vectors):")
print(normalized_vectors)

"""
Now, the vectors have been normalized to unit vectors, each with a magnitude of 1. These unit vectors maintain the relative direction of the original vectors.

"""

Original vectors:
[[3 4]
 [1 2]
 [5 5]
 [2 3]]
Normalized vectors (unit vectors):
[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.70710678 0.70710678]
 [0.5547002  0.83205029]]


'\nNow, the vectors have been normalized to unit vectors, each with a magnitude of 1. These unit vectors maintain the relative direction of the original vectors.\n\n'

##### Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.


In [2]:
"""
Answer:

1. Principal Component Analysis (PCA) is a dimensionality reduction technique widely used in data analysis and machine learning. 
2. Its primary goal is to reduce the dimensionality of a dataset while retaining as much relevant information as possible. 
3. Working of PCA:
a. Standardize the data to ensure that all features have a mean of 0 and a standard deviation of 1.
b. PCA calculates the covariance matrix of the standardized data to understand the relationships between features.
c. PCA then calculates the eigenvectors and eigenvalues of the covariance matrix.
d. The eigenvectors are ranked by their corresponding eigenvalues in descending order. You can choose the top-k eigenvectors to retain in the new 
   feature space, reducing the dimensionality from the original number of features to k.
e. The selected eigenvectors form a new basis for the data, and the original data is projected onto this new basis to create the reduced-dimensional dataset.
4. Example:
"""

from sklearn.decomposition import PCA
import numpy as np

# Create a sample dataset with 3 features and 5 data points
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12],
                 [13, 14, 15]])

# Create a PCA object with 2 components
pca = PCA(n_components=2)

# Fit and transform the data to the new feature space
reduced_data = pca.fit_transform(data)

print("Original data:")
print(data)
print("Reduced data using PCA:")
print(reduced_data)

"""
The dimensionality of the data has been reduced from 3 to 2, retaining the most important information.

"""

Original data:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Reduced data using PCA:
[[ 10.39230485   0.        ]
 [  5.19615242   0.        ]
 [ -0.           0.        ]
 [ -5.19615242   0.        ]
 [-10.39230485   0.        ]]


'\nThe dimensionality of the data has been reduced from 3 to 2, retaining the most important information.\n\n'

##### Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
##### Extraction? Provide an example to illustrate this concept.

In [3]:
"""
Answer:

a. The relationship between PCA and feature extraction can be summarized as follows:
1. Dimensionality Reduction: 
   PCA is primarily used for dimensionality reduction, which is a form of feature extraction. It helps in selecting and creating a smaller number of features 
   that capture the most relevant information in the original data.
2. Preservation of Information: 
   PCA aims to retain as much variance as possible from the original data when creating the new features (principal components). By doing so, it ensures 
   that the most important information in the data is preserved.
3. Linear Transformation: 
   PCA performs a linear transformation of the data by projecting it onto a new orthogonal basis formed by the principal components. 
   These principal components are linear combinations of the original features.

b. Example to illustrate how PCA can be used for feature extraction:
Suppose you have a dataset of images, and each image is represented by a pixel matrix. Each pixel is considered a feature. If you're dealing with 
high-resolution images, you might have thousands or even millions of features, making the dataset challenging to work with. To use PCA for feature extraction 
in this context:
1. Standardize the pixel values to have a mean of 0 and a standard deviation of 1, ensuring all pixels have the same scale.
2. Apply PCA to the standardized pixel data.
3. Select a reduced number of principal components based on the amount of variance you want to retain. For example, 
   you might choose to keep the top 100 principal components out of thousands.
4. The selected principal components serve as the new feature vectors for each image, effectively reducing the dimensionality of the data from 
   thousands of pixels to 100 principal components. These principal components are often much more interpretable and meaningful than individual pixel values.
"""

"\nAnswer:\n\na. The relationship between PCA and feature extraction can be summarized as follows:\n1. Dimensionality Reduction: \n   PCA is primarily used for dimensionality reduction, which is a form of feature extraction. It helps in selecting and creating a smaller number of features \n   that capture the most relevant information in the original data.\n2. Preservation of Information: \n   PCA aims to retain as much variance as possible from the original data when creating the new features (principal components). By doing so, it ensures \n   that the most important information in the data is preserved.\n3. Linear Transformation: \n   PCA performs a linear transformation of the data by projecting it onto a new orthogonal basis formed by the principal components. \n   These principal components are linear combinations of the original features.\n\nb. Example to illustrate how PCA can be used for feature extraction:\nSuppose you have a dataset of images, and each image is represented b

##### Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
##### contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.

In [5]:
"""
Answer:

Using Min-Max scaling to preprocess the data:
a. Understand the Data: Here we have a dataset containing price, rating, and delivery time, which may have different ranges and units.
b. Calculate the Min and Max Values: For each feature, calculate the minimum and maximum values within the dataset.
c. Apply Min-Max Scaling: The formula for Min-Max scaling is:

X_new = X - min(X)/ max(X) - min(X)

where,
     X_new: the scaled value of the feature.
     X: the original value of the feature.
     min(X): the minimum value of the feature in the dataset.
     max(X): the maximum value of the feature in the dataset.
For each feature, apply this formula to transform the values into the [0, 1] range.
d. Updated Dataset: Replace the original values of the features with their Min-Max scaled values.
"""

'\nAnswer:\n\nUsing Min-Max scaling to preprocess the data:\na. Understand the Data: Here we have a dataset containing price, rating, and delivery time, which may have different ranges and units.\nb. Calculate the Min and Max Values: For each feature, calculate the minimum and maximum values within the dataset.\nc. Apply Min-Max Scaling: The formula for Min-Max scaling is:\n\nX_new = X - min(X)/ max(X) - min(X)\n\nwhere,\n     X_new: the scaled value of the feature.\n     X: the original value of the feature.\n     min(X): the minimum value of the feature in the dataset.\n     max(X): the maximum value of the feature in the dataset.\nFor each feature, apply this formula to transform the values into the [0, 1] range.\nd. Updated Dataset: Replace the original values of the features with their Min-Max scaled values.\n'

##### Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
##### features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.

In [1]:
"""
Answer:

Using PCA to reduce the dimensionality of the dataset:
1. The first step will be understanding the dataset and performing necessary data preprocessing, including handling missing values, 
   scaling the data, and ensuring that features are on the same scale.
2. The second step is to standardize the data.
3. Compute the covariance matrix of the standardized data. 
4. Calculate the eigenvalues and eigenvectors of the covariance matrix. These eigenvalues represent the amount of variance explained 
   by each corresponding eigenvector. The eigenvectors are the principal components.
5. Sort the eigenvectors in descending order of their associated eigenvalues.
6. Decide on the number of principal components to retain. 
7. Project the original data onto the selected principal components. This creates a reduced-dimensional dataset with a smaller number of features.
8. Train the stock price prediction model using the reduced dataset, which contains the selected principal components as features.

"""

'\nAnswer:\n\nUsing PCA to reduce the dimensionality of the dataset:\n1. The first step will be understanding the dataset and performing necessary data preprocessing, including handling missing values, \n   scaling the data, and ensuring that features are on the same scale.\n2. The second step is to standardize the data.\n3. Compute the covariance matrix of the standardized data. \n4. Calculate the eigenvalues and eigenvectors of the covariance matrix. These eigenvalues represent the amount of variance explained \n   by each corresponding eigenvector. The eigenvectors are the principal components.\n5. Sort the eigenvectors in descending order of their associated eigenvalues.\n6. Decide on the number of principal components to retain. \n7. Project the original data onto the selected principal components. This creates a reduced-dimensional dataset with a smaller number of features.\n8. Train the stock price prediction model using the reduced dataset, which contains the selected principal

##### Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.


In [5]:
## Program to perform Min-Max scaling to transform the values to a range of -1 to 1.

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Original dataset
data = np.array([1, 5, 10, 15, 20]).reshape(5, 1)

# Create a MinMaxScaler object
min_max = MinMaxScaler(feature_range=(-1, 1))

# Fit and transform the data using the scaler
scaled_data = min_max.fit_transform(data)

print("Original dataset:")
print(data)
print("Min-Max scaled dataset (range -1 to 1):")
print(scaled_data)

Original dataset:
[[ 1]
 [ 5]
 [10]
 [15]
 [20]]
Min-Max scaled dataset (range -1 to 1):
[[-1.        ]
 [-0.57894737]
 [-0.05263158]
 [ 0.47368421]
 [ 1.        ]]


##### Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
##### Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [11]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample dataset (height, weight, age, gender, blood pressure)
data = np.array([
    [170, 65, 30, 1, 120],
    [160, 55, 35, 0, 130],
    [180, 75, 25, 1, 110],
    [175, 70, 28, 0, 125],
])

# Standardize the data
scaler = StandardScaler()
data_standardized = scaler.fit_transform(data)

# Create a PCA object
pca = PCA()

# Fit the PCA to the standardized data
pca.fit(data_standardized)

# Calculate the explained variance for each component
explained_variance = pca.explained_variance_ratio_

# Create a cumulative explained variance plot
cumulative_explained_variance = np.cumsum(explained_variance)

# Determine the number of components to retain (e.g., to explain 95% of the variance)
num_components_to_retain = np.argmax(cumulative_explained_variance >= 0.95) + 1

print("Explained Variance for Each Component:")
print(explained_variance)

print("\nCumulative Explained Variance:")
print(cumulative_explained_variance)



Explained Variance for Each Component:
[8.41790118e-01 1.48670310e-01 9.53957255e-03 1.46733664e-33]

Cumulative Explained Variance:
[0.84179012 0.99046043 1.         1.        ]
